spring:
  application:
    name: starzz-boot
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  security:
    password-reset-sentinel: resetRequired
    jwt-secret: ${JWT_SECRET}
    jwt-expiration: 86400000
  admins:
    - admin1
    - admin2
    - admin3
